### ISSUE TITLE
[indexer-balances] indexing stopped at block height 22633808

### ISSUE THREAD

**Issue by sarin59337** [near/near-microindexers#50]
Indexing stopped at block height 22633808 with the following error:
```
2023-12-02T11:30:57.136777Z ERROR indexer_balances: Stop indexing due to 1 changes for receipts were not applied, block_height 22633808
{
    6QKTEHsLihDgVrdtWYbURA28zF29Xdw5dnfWbDVWHPv4: AccountWithBalance {
        account_id: AccountId(
            "aspaceodyssey2001.near",
        ),
        balance: BalanceDetails {
            non_staked: 5087754972079500200000000,
            staked: 0,
        },
    },
}
Error: 1 changes for receipts were not applied, block_height 22633808
{
    6QKTEHsLihDgVrdtWYbURA28zF29Xdw5dnfWbDVWHPv4: AccountWithBalance {
        account_id: AccountId(
            "aspaceodyssey2001.near",
        ),
        balance: BalanceDetails {
            non_staked: 5087754972079500200000000,
            staked: 0,
        },
    },
}
```

**Comment by sarin59337** [comment]
@morgsmccauley @telezhnaya @khorolets any suggestions on how to proceed? Thanks!

**Comment by telezhnaya** [comment]
Thank you for reporting!
We have the same issue in indexer-for-explorer https://github.com/near/near-indexer-for-explorer/issues/328
Quickfix: start the indexer from the next block, 22633809
After some time (~10 minutes) run one more indexer just to collect missing 22633808 block

The reason of this issue is an extremely weird situation in nearcore. As far as we know, it never happens again.
I knew the answer because I just remember this number 22633808

**Comment by telezhnaya** [comment]
be sure you use RPC-based balance mode during these tweaks https://github.com/near/near-microindexers#what-is-balance-mode-for-indexer-balances
